name: CI

on: [push, pull_request]
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}

      # Add to Heroku
      - name: Remote to heroku
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME}}.git
      
      # Deploy to Heroku
      - name: Filter shallow
        run: git filter-branch -- --all
      - name: Deploy to Heroku
        run: git push heroku main --force
